server:
  port: 8082

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/rowitech
    password: koberflow
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
